### ISSUE TITLE
Adds Items to Tab Where It Exists Instead of Current Tab

### ISSUE THREAD

**Issue by sirj0k3r** [EnderHDMC/MHWISaveEditor#14]
I'm not sure this is a bug or a feature (to avoid having the same item on different tabs) but here it goes anyways...

**Steps to Reproduce**
1- Deselect **Search All Tabs** checkbox;
2- Check your **Item Box** for an item you have there but not on your **Item Pouch**;
3- Select the **Item Pouch** tab;
4- Use the textbox to search for that item;
5- Click **Add**;
6- Watch how it adds it to the **Item Box** instead of the **Item Pouch**;

PS: I'm not sure if this project is still being maintained but I still wanted to share.
PPS: If it's still being maintained I should add that **adding** equipment on the **Equipment Editor** would also be a nice feature to have.

**Comment by EnderHDMC** [comment]
That is intended behaviour.
The editor adds items to your equipment box and puts them in the correct category, to ensure users don't add monster materials or decoration items to their item pouch for example.

I could change this in a later update, to make it more intuitive.
With your feedback, I'd consider rather checking if the current page can store that item and add it there, else give a message saying it can't be added there.

The project is still being maintained, I just haven't worked on it lately as life has gotten busy with classes and projects.
Adding equipment to the equipment box is planned for the next update.

**Comment by EnderHDMC** [comment]
Opened an issue for the PPS: #33
