### ISSUE TITLE
Easier item searching

### ISSUE THREAD

**Issue by EnzoCALL** [EnderHDMC/MHWISaveEditor#2]
This includes a way to quickly look for a specific item (exemple : you want to get more immortal reactors, type it in a search bar or something so you don't have to scroll all the way down !)

(Lovely mod there, I'm looking forward to see how much you'll improve it !)

**Comment by EnderHDMC** [comment]
Thanks for the suggestion, it'll be added to the to-do list.

**Comment by EnderHDMC** [comment]
Added an Item Search Function (commit b113da08ae3306e99b50cb97c2b53979b521899d)
This has been released on [Releases\0.1.2](https://github.com/EnderHDMC/MHWISaveEditor/releases/tag/0.1.2).
