### ISSUE TITLE
Add Yukumo Layered Loadout option doesn't work

### ISSUE THREAD

**Issue by ToniLp22** [EnderHDMC/MHWISaveEditor#22]
Why the "Add Yukumo Layered Loadout" option doesn't work? The rest of the limited unlocks do work.

**Comment by EnderHDMC** [comment]
The DLC layered can't be added through save edits.
So what that option does is that it "gives" you a Layered Loadout which lets you set that layered.

There should be a hotkey under the layered menu to check your Loadouts.
The Yukumo layered will be in there.

**Comment by ToniLp22** [comment]
@EnderHDMC Ohh ok, thanks you! I didn't remember that option in the layered menu.
