### ISSUE TITLE
System Error when trying to open the save editor

### ISSUE THREAD

**Issue by ThisIsDogMan** [EnderHDMC/MHWISaveEditor#23]
After downloading the save editor and opening it, I get a system error "The code execution cannot proceed because VCRUNTIME140_1.dll and MSVCP140_1.dill was not found. Reinstalling the program may fix this problem. I kept reinstalling the SaveEditorSetUp but the same issue keeps happening. How do I get those 2 missing files?

**Comment by ThisIsDogMan** [comment]
nvm after a good while progressing though the game I gave the file another go and it started working

**Comment by EnderHDMC** [comment]
If it gives this issue, then that means VC_Redist is not installed.
