### ISSUE TITLE
Chinese Translation help

### ISSUE THREAD

**Issue by Narugakuruga** [EnderHDMC/MHWISaveEditor#4]
Hi there. I really appreciate the effort to make a save editor. So I want to help add Chinese translation..
I'm very familiar with the game and good at translations.
I can't code but want to add a hand.

**Comment by EnderHDMC** [comment]
I've added instructions for translation.
https://github.com/EnderHDMC/MHWISaveEditor#translation

Just keep in mind that the editor currently does not detect the translations.
I will upload a pre-release soon that will allow you to load your translation into the save editor.

**Comment by EnderHDMC** [comment]
I have released version 0.1.5.

This version will now detect the translation files in res/translations and allow you to select them.
New strings have been added, so there are things to translate.
Some strings have also been slightly changed, so their translations are now obsolete, these have been marked as incomplete translations, but the editor will load them still.

If someone would like to translate the new stuff, they're welcome to submit a Pull Request for it.
