### ISSUE TITLE
Failed to load monster hunter data

### ISSUE THREAD

**Issue by Theepicone360** [EnderHDMC/MHWISaveEditor#8]
yep it's just waht it says, whenever i edit it it tends to give me that
NOTE:
i just edited the steam id and tried to give myself assassins hood and hood +, layered armor bayek and artemis
and lastly artemis set but thats all and after i check those, i save (successfully saved btw)
i run mh and it just gives me that error
thankfully the mod you guys made has an automatic backup system.
but i really do want that assassin hood so badly

**Comment by EnderHDMC** [comment]
Are you sure you put in the correct Steam ID?
If you go to [SteamDB Calculator](https://steamdb.info/calculator/) and put in your account, the thing that the Save Editor expects is the `64-bit SteamID` that can be seen there.

You wouldn't need to change your Steam ID unless you're transferring a save file from another Steam account.
